### ISSUE TITLE
Bug when running src/PrecisionProDB.py

### ISSUE THREAD

**Issue by Joaodemeirelles** [ATPs/PrecisionProDB#3]
https://github.com/ATPs/PrecisionProDB/blob/825df172c6f78fbe66b3d153ab7906bd818614ba/src/perChrom.py#L523C24-L523C32

This line of code on perChrom.py is missing the ":" and, if I'm correct, the identation of this code block from 524 to 527.

**Comment by ATPs** [comment]
Thank you for pointing out this error. 

```
        if codons_alt['AA_index'].isnull()
        codons_alt.loc[codons_alt.duplicated('AA_index'),['codon_ref','AA_ref','AA_index']] = np.NaN # only use each AA_ref Once
        codons_alt['AA_alt'] = codons_alt.apply(lambda x:x['AA_ref'] if x['codon_alt'] == x['codon_ref'] else str(Seq(x['codon_alt']).translate()), axis=1)
        codons_alt['AA_index'] = codons_alt['AA_index'].fillna(method='ffill')
        new_AA = str(''.join(codons_alt['AA_alt']).split('*')[0])
```
line 523 should not exist. 

I introduced this error here https://github.com/ATPs/PrecisionProDB/commit/c6ce1753b439ca9837bb69e5fb5cb83f21632c96

Just delete line 523
