### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by prao123** [ATPs/PrecisionProDB#4]
Hello,
I am running PrecisionProDB using our own vcf file generated from FreeBayes. While the example files run through fine without errors, the output produced on my own file is not generating any fasta files. The command I have run is this:
` ~/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB.py -m A375p11r3.vcf -g Uniprot_files/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz -p Uniprot_files/UP000005640_9606.fasta.gz -f Uniprot_files/Homo_sapiens.GRCh38.112.gtf.gz -o A375_ss_vcf_variant_hg38
`
The output is:
`variant file is a vcf file
start extracting mutation file from the vcf input
individual is None, select the first sample in vcf file, which is A375p11r3
before QC, sites with mutations: 0 of which, homozyous sites: 0
after QC, number of variants in two dataframes are: 0 0
finished extracting mutations from the vcf file
start running PrecisionProDB for first strand of the genome mutation file
datatype is not provided. Try to infer datatype. Note: Ensembl datatype cannot be inferred.
input data is inferred as from Ensembl_GTF. Use with caution!
split the genome, mutation, gtf and protein file based on chromosomes
finish splitting the genome file
cannot determine chromosome for proteins based on protein_keyword: protein_id
finish assign chromosome for each protein
finish splitting the protein file
finish splitting the mutation file
finish splitting the gtf file
number of chromosomes with proteins: 0
Traceback (most recent call last):
  File "/home/prao/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB.py", line 94, in <module>
    runPerGenoVCF(file_genome = file_genome, file_gtf=file_gtf, file_mutations = file_mutations, file_protein=file_protein, threads=threads, outprefix=outprefix, datatype=datatype, protein_keyword=protein_keyword, filter_PASS=filter_PASS, individual=individual, chromosome_only=chromosome_only)
  File "/home/prao/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB_vcf.py", line 56, in runPerGenoVCF
    pergeno_1.runPerChom()
  File "/home/prao/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB_core.py", line 556, in runPerChom
    df_mutAnno = pd.concat([pd.read_csv(f, sep='\t') for f in files_mutAnno], ignore_index=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prao/miniconda3/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/prao/miniconda3/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prao/miniconda3/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
` 
Could you please let me know if you see any issues? Thanks

**Comment by ATPs** [comment]
Hi. Based on the log, it seems that the vcf file is empty or it is in some special format not recognized by the program. Can you double check or show a few lines of the vcf file?

**Comment by prao123** [comment]
Hello,
I checked the vcf file. It has variants noted as per the format. I ran bcfstats on it and it produces results as expected. I have attached a few lines as a notepad file:
[vcf_few_lines_vcf.txt](https://github.com/user-attachments/files/15798833/vcf_few_lines_vcf.txt)

Thanks

**Comment by ATPs** [comment]
Hi, I checked and found that the vcf file you provided do not have keyword "PASS" in the "FILTER" column. In default, "PASS" is required and variants with no keyword "PASS" will not be considered. You may need to run with the option `--no_filter` to avoid filtering "PASS".
Thank you and let me know if you have further question.

Xiaolong

**Comment by prao123** [comment]
Hello Xiaolong,
Thank you for your response. Adding the --no_filter parameter did count the number of mutations to more than 0. However, the program still fails. Heres the code I ran and the output log below:
`python ~/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB.py -m wes_hg38_dbsnp_filt_id_vcf.vcf --no_filter -g Homo_sapiens.GRCh38.dna.primary_assembly.fa -p Homo_sapiens.GRCh38.pep.all.fa.gz -k "transcript_id" -f Homo_sapiens_GRCh38_fixed.gtf -o A375_ss_vcf_variant_hg38`

`Namespace(genome='Homo_sapiens.GRCh38.dna.primary_assembly.fa', gtf='Homo_sapiens_GRCh38_fixed.gtf', mutations='wes_hg38_dbsnp_filt_id_vcf.vcf', protein='Homo_sapiens.GRCh38.pep.all.fa.gz', threads=36, out='A375_ss_vcf_variant_hg38', datatype='gtf', protein_keyword='transcript_id', no_filter=True, sample=None, all_chromosomes=False, download='', uniprot='', uniprot_min_len=20, PEFF=False)
variant file is a vcf file
start extracting mutation file from the vcf input
individual is None, select the first sample in vcf file, which is unknown
before QC, sites with mutations: 769928 of which, homozyous sites: 572004
after QC, number of variants in two dataframes are: 575948 767726
finished extracting mutations from the vcf file
start running PrecisionProDB for first strand of the genome mutation file
datatype is not provided. Try to infer datatype. Note: Ensembl datatype cannot be inferred.
input data is inferred as from Ensembl_GTF. Use with caution!
split the genome, mutation, gtf and protein file based on chromosomes
finish splitting the genome file
cannot determine chromosome for proteins based on protein_keyword: transcript_id
finish assign chromosome for each protein
finish splitting the protein file
finish splitting the mutation file
finish splitting the gtf file
number of chromosomes with proteins: 0
Traceback (most recent call last):
  File "/home/prao/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB.py", line 94, in <module>
    runPerGenoVCF(file_genome = file_genome, file_gtf=file_gtf, file_mutations = file_mutations, file_protein=file_protein, threads=threads, outprefix=outprefix, datatype=datatype, protein_keyword=protein_keyword, filter_PASS=filter_PASS, individual=individual, chromosome_only=chromosome_only)
  File "/home/prao/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB_vcf.py", line 56, in runPerGenoVCF
    pergeno_1.runPerChom()
  File "/home/prao/Software/PrecisionProDB/PrecisionProDB-1.1.2/src/PrecisionProDB_core.py", line 556, in runPerChom
    df_mutAnno = pd.concat([pd.read_csv(f, sep='\t') for f in files_mutAnno], ignore_index=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prao/miniconda3/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/prao/miniconda3/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prao/miniconda3/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate`
 
I tried it with both the genome, gtf and Uniprot/ Ensembl files that I can download (from the download.sh script) or using my own gtf, genome and Ensembl pep.all files (hg38). It errors out wih the same error everytime. 

Thanks

**Comment by ATPs** [comment]
Ah, I will check why that happened and let you know once I find the problem.
Thank you 

Xiaolong

**Comment by ATPs** [comment]
hi, I just checked. 

So, if use Ensembl gtf file, then the datatype , should be "Ensembl_GTF" and you do not need to set `-k "transcript_id"`. In fact, the datatype is set to "protein_id".

```
            elif self.datatype == 'RefSeq' or self.datatype == 'Ensembl_GTF':
                self.protein_keyword = 'protein_id'
```
The reason is Ensembl, GENCODE or RefSeq, each of their GTF file is with some special settings so we have to do some customization. 


```ini
 -a {GENCODE_GTF,GENCODE_GFF3,RefSeq,Ensembl_GTF,gtf}, --datatype {GENCODE_GTF,GENCODE_GFF3,RefSeq,Ensembl_GTF,gtf}
                        input datatype, could be GENCODE_GTF, GENCODE_GFF3, RefSeq, Ensembl_GTF or gtf. default "gtf". Ensembl_GFF3 is not supported.
```

the `-k "transcript_id"` is used to match the protein ids in the GTF file with proteins provided in the protein sequence file. 
Please note that `--protein PROTEIN`, a file matching with the GTF file is required, not uniprot sequences. If you want uniprot sequences, you have to supply with the option `-U UNIPROT, --uniprot UNIPROT`.

I just test the run with ensembl and it works. below is my script

```bash
 python downloadHuman.py -d Ensembl -o /data/temp
python PrecisionProDB.py -m /data/temp/vcf_few_lines_vcf.vcf -g /data/temp/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz --no_filter -t 1 -p /data/temp/Homo_sapiens.GRCh38.pep.all.fa.gz  --gtf /data/temp/Homo_sapiens.GRCh38.112.gtf.gz -o /data/temp/20260613 -a Ensembl_GTF
```

I hope this works.

Thank you.

Xiaolong

**Comment by prao123** [comment]
Thank you for testing out my file. I will run it through and let you know if I encounter any issues.

Cheers!

**Comment by prao123** [comment]
Hello, The code (as you had typed it) worked well for my vcf file. For some reason, it is not working with Uniprot fasta file (which I am in need of) and I was not able to fully understand how to put in the right flags for Uniprot fasta sequences. Could you please help me by write a script that includes Uniprot files?
Thanks.

**Comment by ATPs** [comment]
-U UNIPROT, --uniprot UNIPROT

use the option above to supply uniprot sequence in addition to the working script you use now.

**Comment by prao123** [comment]
Hello,
Just for reference, I used the code from this page to run the script and it completed without issues.
https://github.com/ATPs/PrecisionProDB/tree/master/examples/UniProt

Thanks
